### PR TITLE
Serve your domain

### PR DESCRIPTION
**Pull request by cal27279**
Hi @catlook . Could you please review:edit when you have a chance?

### CODE REVIEW

**Comment by catlook** [comment]
@cal27279 review my edits and see if you agree.  Note: You might consider changing the permalink and folder name to match the article title.  If you do that, add a redirect from the old name to the new name by following the instructions in Contributing.md.

**Review by cal27279 — COMMENTED** [review]
Thank you @catlook I agree with your changes.

**Comment by cal27279** [comment]
Hi @catlook I've just changed the title to match the permalink and it built.

**Comment by catlook** [comment]
Unfortunately, the new title was actually the better choice. An action verb, rather than a gerund.  That's why I suggested changing the other two. However, all three matching is better than a mismatch.

**Pull request merged**
