### PR TITLE
Create new article about live migrations

### PR DESCRIPTION
**Pull request by csilva235**
New article covering some FAQs about Live Migrations. Since Live Migrations are meant to be non-impacting, we'd like to have a document that customers can view when the live migration is unsuccessful and requires a reboot migration.

### CODE REVIEW

**Review by cal27279 — APPROVED** [review]
Thank you @stephamon , I agree with your edits.

**Comment by csilva235** [comment]
Just noticed a little issue with the document as there appears to be some language geared towards an internal audience. 

Line 25 of the most recent version states

`When you can't perform
live migrations or a customer doesn't allow you to do so, you can perform an
alternative method known as a *reboot migration*.`

Can that bit be removed?

**Comment by cal27279** [comment]
@csilva235 Would you please take a look at the new changes when you have a chance?

**Review by stephamon — APPROVED** [review]
Looks good to me!

**Review by viridaria — APPROVED** [review]

**Pull request merged**
