### PR TITLE
Create new article - Slow Windows Login

### PR DESCRIPTION
**Pull request by csilva235**
New article created by FLR.

### CODE REVIEW

**Comment by cal27279** [comment]
I've already taken care of this PR, it's on PR1134

**Comment by cal27279** [comment]
Same as: https://github.com/rackerlabs/support-how-to/pull/1134

**Comment by catlook** [comment]
@cal27279 review my edits and see if you agree :). Also, don't forget to use a numbered list for sequential steps.

**Comment by catlook** [comment]
shifting my edits to #1134.  Go ahead and close this PR.

**Pull request closed without merging**
