### PR TITLE
Update RackConnect Global FAQ article per Peter Gilani

### PR DESCRIPTION
**Pull request by cal27279**
Hi @catlook Could you please review and update this PR when you have a chance? Thanks!

### CODE REVIEW

**Comment by catlook** [comment]
@cal27279 review my edits and see if you agree :). I also converted this to our standard FAQ accordion formatting.

**Comment by catlook** [comment]
stand by while I address the build fail

**Review by cal27279 — COMMENTED** [review]
Thanks @catlook I agree with your edits =)

**Comment by catlook** [comment]
@cal27279 good to go!

**Comment by catlook** [comment]
@cal27279 good to go!

**Review by catlook — APPROVED** [review]

**Pull request merged**
