### PR TITLE
Mfa changes2

### PR DESCRIPTION
**Pull request by viridaria**

### CODE REVIEW

**Comment by catlook** [comment]
@viridaria review my edits and see if you agree :)

NOTE: Our Style Guide specifies "multifactor" instead of "multi-factor".  I made the changes where appropriate.  I left "multi-factor" in place when it referred to screens or menu options. I also updated the permalink.  Please update the folder name to remove the dash in multifactor.

**Comment by catlook** [comment]
Hold up a second...when the multi-factor with a hyphen is on the control panel or button, we actually have to leave it in place!  Unless we can talk the UX folks into removing it.

**Review by cal27279 — APPROVED** [review]
lgtm!

**Comment by viridaria** [comment]
errors replacing multifactor instead of multi-factor

**Pull request closed without merging**
