### PR TITLE
Audit mailboxes

### PR DESCRIPTION
**Pull request by viridaria**

### CODE REVIEW

**Comment by catlook** [comment]
@viridaria looks like you removed the add-mailboxes-sci.png image in this PR, so I'm deleting the reference in the md file while I do edits.  Hopefully, it builds!

**Comment by catlook** [comment]
still editing...please stand by!  will finish shortly

**Comment by catlook** [comment]
@viridaria review my edits and see if you agree :)

**Review by cal27279 — APPROVED** [review]
lgtm

**Pull request merged**
