### PR TITLE
Cloud networks faq

### PR DESCRIPTION
**Pull request by AnaMCD-lab**
Hi @catlook, can you please review?, no changes, last updated by you, there are some accordion directives in HTML that I left but didn't display pretty on my VSC viewer. Thanks

### CODE REVIEW

**Comment by catlook** [comment]
@AnaMCD-lab this PR picked up a copy of the DC article, so be sure to remove it before merging!

**Comment by catlook** [comment]
@AnaMCD-lab review my edits and see if you agree :). I made my usual edits, but I noticed the cURL example was unclear.  I compared it to the API guide and cleaned it up.  I also indented it so the example actually displays properly in the preview.

The VSC viewer does a great job rendering the markup, but when in doubt, use the git preview function.  Do you know how to do that?  Ping me!

**Comment by catlook** [comment]
@AnaMCD-lab don't forget to add the audit label to your audits

**Comment by AnaMCD-lab** [comment]
Now that I see the doc in github, A lot of the markdown code might have been hidden so I didn't review thoroughly. I'll check the DC file

**Review by cal27279 — APPROVED** [review]
Good to go

**Pull request merged**
