### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by irisgarciagv**

### CODE REVIEW

**Comment by irisgarciagv** [comment]
@lfielder

**Comment by ssalinas24** [comment]
@lfielder FYI we still have a majority of dedicated users on MyRack. Which these instructions are for. The minority is on CTUI/Fabric. Do you still prefer to delete these at this moment? Optionally we could add sections for each one of these to describe the current CTUI flow to get us through the releases. Then decomm the MyRack doc versions later.

**Comment by lfielder** [comment]
I think attempting to keep these documents up to date is too much work given we have zero writers. The goal here is to remove these documents after phase 2 of GA release. Then most of the users will be on the new ticketing UI. Also we need another PR to add a new article describing all the templates and what triggers them.

**Comment by ssalinas24** [comment]
Correct. The PR for adding new CTUI/Fabric Ticketing should be priority at this moment. Not the deletion PR. This Deletion PR should just hold off till Phase 2 you mentioned.

**Comment by ssalinas24** [comment]
We are no longer going to delete these articles. Instead, we will be updating and moving these articles in other PRs.

**Pull request closed without merging**
