### PR TITLE
Toosalgado18project 2

### PR DESCRIPTION
**Pull request by AnaMCD-lab**
New article: equest-for-additional-ips. Hi @catlook, can you please review when you have a chance? Thanks! ☺️

### CODE REVIEW

**Comment by catlook** [comment]
@AnaMCD-lab review my edits and see if you agree :)

**Comment by catlook** [comment]
Stand by.  I changed the title of the article, so I need to also change the folder title for the image.

**Comment by catlook** [comment]
fixing build problem because of rename

**Review by cal27279 — APPROVED** [review]
:shipit:

**Pull request merged**
