### PR TITLE
audit-email-plus

### PR DESCRIPTION
**Pull request by viridaria**

### CODE REVIEW

**Comment by catlook** [comment]
@viridaria according to this 
(https://forum.odrive.com/t/amazon-cloud-drive-post-11-2020/7839), Cloud Drive for Desktop is discontinued.  Is that true?  Edits made.

**Comment by viridaria** [comment]
@catlook Got confirmation that it is still relevant from Jon Muckenfuss 
The Cloud Drive for Desktop is still able to be downloaded

**Comment by catlook** [comment]
Perfect...proceed apace!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Review by cal27279 — APPROVED** [review]
lgtm!

**Pull request merged**
