### PR TITLE
Create new article - Sophos error on EOL Windows server

### PR DESCRIPTION
**Pull request by csilva235**
New article by FLR.

### CODE REVIEW

**Comment by csilva235** [comment]
Apologies, but as Sophos is a dedicated only product, this will likely need to be moved to the dedicated hosting section.

**Comment by cal27279** [comment]
https://github.com/rackerlabs/support-how-to/pull/1137

**Comment by catlook** [comment]
@cal27279 review my edits and see if you agree :) FYI:
If a contributor includes the title as a heading in the first line, remove it.

Headings should start at level three (###) and there should be a blank line before and after each heading.

Headings usually don’t end with punctuation like periods and colons.

Headings are sentence case.

The “it is” contraction needs a comma.

Articles should end with a blank line.

**Comment by cal27279** [comment]
Thank you @catlook I agree with you comments and have added your comments to my guidelines =)

**Review by viridaria — APPROVED** [review]

**Pull request merged**
