### PR TITLE
Audit files: set-up-an-imap-account-on-a-windows-phone, folder name changed

### PR DESCRIPTION
**Pull request by AnaMCD-lab**
Hi @catlook, can you please review and see if you agree :)?

### CODE REVIEW

**Comment by catlook** [comment]
@AnaMCD-lab, review my edits and see if you agree :). Also,  I trecommend actually getting rid of the screenshots. They don't add anything or show a greater context.  The text provides everything, I think.

**Comment by catlook** [comment]
DOn't forget to add the audit label to full audits.

**Comment by catlook** [comment]
You need to also remove the references to the images in the index.md file

**Review by cal27279 — APPROVED** [review]
lgtm

**Pull request merged**
