### PR TITLE
Create article - Using SFTP and SCP

### PR DESCRIPTION
**Pull request by toosalgado18**
Article created by FLR

### CODE REVIEW

**Comment by catlook** [comment]
@toosalgado18 Hey, welcome to content contribution, Miguel!!  Glad to have you aboard :). I just did a quick spot check of the metadata and noted one thing:  It should be as follows for this article:

product: Cloud Servers
product_url: cloud-servers

I know it's confusing but the product and product_url are sometimes the same but often different. To find out the correct text, check out the CONTRIBUTING.md file, near the bottom.  (https://github.com/rackerlabs/support-how-to/blob/master/CONTRIBUTING.md)

**Comment by catlook** [comment]
@toosalgado18 Did you mean to close this before we published it?

**Comment by AnaMCD-lab** [comment]
I am still working on it...

**Comment by catlook** [comment]
I messaged the contributor, and he'll reopen if he closed it by accident.

**Pull request closed without merging**
