### PR TITLE
Toosalgado18 project

### PR DESCRIPTION
**Pull request by AnaMCD-lab**
New articles: mariadb-error-log-configuration, install-imap-for-php71-on-ubuntu, ssl-basics, unable-to-install-plugins-in-wordpress, vhost-and-server-blocks-basics, uploads several articles into one PR to avoid more confusion. Hi @catlook, can you please review these articles? Thanks!

### CODE REVIEW

**Comment by catlook** [comment]
@AnaMCD-lab review my edits and see if you agree :). Here are my notes on some of the things I corrected: 

- Headings and titles should be sentence-case.
- Files, directories, and URLs are usually bolded rather than monospaced.
- Headings should have a blank line before and after them, and have no fewer than three # signs.
- Lead-in phrases, such as “By default”, are usually followed by a comma.
- Use “and so on” instead of on “etc” (In general, relate Latin phrases with an English equivalent).
- Use hyphens for compound adjectives or adverbs, such as “DDL-related messages”.
- Trademark the first occurrence of a trademarked name and not the subsequent occurrences. \
- Don’t forget to use the Oxford (or serial) comma. Steps are usually in an ordered (or number list).
- It’s weird but for Ubuntu, we usually have to say “the Ubuntu operating system”.  For all others, such as Centos OS, we just say the name. Ask Stephanie if you have questions about that.
- We usually don’t trademark our own name, Rackspace.
- Look for opportunities to make headings consistent (all start with a verb, for example.
- All articles should end with one and only one blank line. 
- Watch out for passive voice and unwanted future tenses.
- Make sure to put a space after a period before starting the next sentence.
- Make sure product and company names are appropriately and consistently capitalized.
- Look for opportunities to reformat content into lists or tables to make it easier to read and use.
- You generally don’t need to start sections with “How to …”.
- If you have time, it helps to view the preview to make sure the formatting works as expected and looks good. For example, some of the sample code was too hard to read with the original formatting.

**Review by cal27279 — APPROVED** [review]
lgtm

**Review by cal27279 — COMMENTED** [review]
HI @AnaMCD-lab  Quick question, should there be an audit date for this article? I kinda feel there ought to be one. Please advise.

**Comment by AnaMCD-lab** [comment]
Changes requested done, thanks.

**Review by cal27279 — APPROVED** [review]
lgtm

**Pull request merged**
