### PR TITLE
create-site-seal-code

### PR DESCRIPTION
**Pull request by viridaria**

### CODE REVIEW

**Comment by catlook** [comment]
@viridaria, review my edits and see if you agree :) Also, I renamed the folder and matched the permalink to the article title

**Comment by catlook** [comment]
hmmm...figuring it out ...

**Comment by catlook** [comment]
@viridaria, review my edits and see if you agree :) Also rename permalink and the folder for the article and image to:  add-a-site-seal-to-your-website

**Comment by viridaria** [comment]
done, thanks @catlook

**Comment by catlook** [comment]
thank YOU @viridaria !!

**Review by cal27279 — APPROVED** [review]
:shipit:

**Pull request merged**
