### PR TITLE
Upgrade apache http server 2.2 to 2.4 in rhel and centos

### PR DESCRIPTION
**Pull request by AnaMCD-lab**
Hi @catlook, can you please review and merge? I set you as reviewer, the label is 'review:editor' and the pr assigned to me. Hope this is ok.

### CODE REVIEW

**Comment by catlook** [comment]
@AnaMCD-lab review my edits and see if you agree :). Also, looks like this PR accidentally picked up the relay article.  Because that's already in another PR, remove it from this one.

**Comment by catlook** [comment]
@AnaMCD-lab FYI, I generally edit but do not review and merge the same PR.  THe process is, ask me to edit, and then as a teammate to review and merge.  I see that extra file is still in this PR.  If you can't get rid of it, you might have to save the edited version of the upgrade apache article, delete this PR, close the branch, make a new branch and PR.  Make sense?

**Comment by catlook** [comment]
Oh, and when you're ready for the teamie review, put the review-peer label on the PR.

**Review by cal27279 — APPROVED** [review]
:shipit:

**Pull request merged**
