### PR TITLE
retires article

### PR DESCRIPTION
**Pull request by cal27279**
I found this article while trawling our how-to website. Initially couldn't find it the content folder. Found it in the "retired" folder. I'm making sure it's retired.

### CODE REVIEW

**Review by viridaria — APPROVED** [review]

**Review by viridaria — APPROVED** [review]

**Review by robb-romans — CHANGES_REQUESTED** [review]
Hi Carlos. I think you want to redirect this to the retired articles page, and not return the 404 not found error code.

**Comment by cal27279** [comment]
> Hi Carlos. I think you want to redirect this to the retired articles page, and not return the 404 not found error code.

On it @robb-romans

**Review by cal27279 — COMMENTED** [review]
Hi @robb-romans , I've taken care of the changes you requested =). This PR doesn´t build well for some reason. Ravi helped me deploy it successfully. I'll ask him to take a look at it first Monday first thing to get rid of the Netlify build error.

**Review by robb-romans — APPROVED** [review]
Thanks!

**Comment by robb-romans** [comment]
The error was the build did not find the Algolia key. Worked after clearing cache and rebuilding. @codebyravi  can investigate root cause.

**Comment by cal27279** [comment]
Thanks @robb-romans You're awesome!

**Pull request merged**
